version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 8000:80
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
